version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17 # 자바 버전에 따라 11 또는 17로 수정 가능
    commands:
      - echo Installing dependencies...
      - chmod +x ./gradlew # 실행 권한 부여
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build # Gradle 빌드 실행
  post_build:
    commands:
      - echo CI Pipeline Stage 1 Completed!

artifacts:
  files:
    - 'build/libs/*.jar' # 빌드 결과물인 jar 파일만 저장
    - 'appspec.yml'      # (나중에 CD 단계에서 필요)
    - 'scripts/**/*'     # (나중에 CD 단계에서 필요)
  discard-paths: yes
